name: Build Mod

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build
        run: ./gradlew build --no-daemon

      - name: Upload mod
        uses: actions/upload-artifact@v4
        with:
          name: EscRemap
          path: build/libs/*.jar
